---
title: "Pertemuan 2-3"
author: "Deni Permana"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sorting dan dasar Visualisasi

## Sorting

```{r}
library(dslabs)
data(murders)
View(murders)
```

Nampilin total

```{r}
murders$total
```

## Fungsi Sort()

```{r}
urutan_asc = sort(murders$total)
urutan_desc = sort(murders$total, decreasing = TRUE)

urutan_asc
```
```{r}
urutan_desc
```

## Fungsi Order()

```{r}
index_urutan_asc = order(murders$total)
index_urutan_desc = order(murders$total, decreasing = TRUE)

index_urutan_asc
```
```{r}
# index_urutan_desc
murders$state[index_urutan_desc]
```
## Fungsi Rank()

```{r}
x <- c(5,2,9,1,7)
rank(x)
```

```{r}
rank(-x)
```

## Fungsi max() dan which.max()

```{r}
terbesar <- max(murders$total)
terkecil <- min(murders$total)

index_terbesar <- which.max(murders$total)
index_terkecil <- which.min(murders$total)

# terbesar
# terkecil

index_terbesar
index_terkecil

murders$state[index_terbesar]
murders$state[index_terkecil]
```

## Dasar Visualisasi Data

## Plot

```{r}
populasi = murders$population / 10^6
total = murders$total

plot (
  populasi,
  total,
  main = "Total Pembunuhan Tiap Populasi", #Judul
  xlab = "Populasi (Per 1 Juta Jiwa)",
  ylab = "Total Pembunuhan",
  pch = 19
)

```

## Line Plot

```{r}
data_bbm = data.frame(
  tahun = c(2000:2016),
  harga = c(
    1150, 1450, 1750, 1810, 2400, 
    4500, 4500, 4500, 6000, 5000, 
    4500, 4500, 4500, 6500, 8500, 
    7400, 6550
  )
)

# data_bbm
plot(
  data_bbm$tahun,
  data_bbm$harga, 
  type = "l",
  # type = "p"
  main= "Harga Pemium Tahun 2000-2016"
)

```

## Barplot

```{r}
barplot(
  data_bbm$harga ~ data_bbm$tahun,
  las = 2,
  xlab = "Tahun",
  ylab = "Harga"
)

```

## Histogram

```{r}
nilai_ujian = c(
  100, 100, 100, 0, 85, 0, 100, 95, 90, 100,
  90, 0, 100, 75, 100, 85, 88, 90, 88, 100, 
  60, 75, 85, 45, 40, 45, 40, 50, 60
)

# nilai_ujian
hist(
  nilai_ujian,
  main = "Frekuensi Nilai Ujian",
  xlab = "Nilai Ujian",
  ylab = "Frekuensi",
  col = "yellow"
)
```

## Boxplot

```{r}
murders$rate = murders$total / murders$population * 1000000

# View(murders)
boxplot (
  rate~region,
  data = murders,
  main = "Tingkat Pembunuhan Tiap region",
  xlab= "Nama Region",
  ylab = "Tingkat Pembunuhan (%)"
)
```

